server:
  port: 8001

spring:
  application:
    name: pay-payment-service

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test

  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: localhost
        heartbeat:
          enabled: true
mybatis:
  mapper-locations: classpath:mapper/*.xml
