server:
  port: 8002

spring:
  application:
    name: pay-order-service

eureka:
  client:
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:7001/eureka
    fetch-registry: true
  instance:
    instance-id: ${spring.application.name} # 配置主机名称
    prefer-ip-address: true # 显示IP
    lease-renewal-interval-in-seconds: 1 # 发送心跳包间隔时间
    lease-expiration-duration-in-seconds: 2 # 销毁等待时间上限
