server:
  port: 8002

spring:
  application:
    name: pay-order-service

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        service-name: ${spring.application.name}
        hostname: localhost
        heartbeat:
          enabled: true
