server:
  port: 8002

spring:
  application:
    name: pay-payment-service

  datasource:
    url: jdbc:mariadb://localhost:3306/test
    username: test
    password: test
mybatis:
  mapper-locations: classpath:mapper/*.xml
